image:
  repository: 959413831332.dkr.ecr.eu-central-1.amazonaws.com/greeter
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 2

env:
  HELLO_TAG: "dev"

service:
  port: 8080
  type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

ingress:
  enabled: true
  className: public-ingress
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi