# .github/workflows/build-and-push.yml
name: Build & Push
on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 959413831332
  ECR_REPOSITORY: greeter

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/eks-ci-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
            | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build & Push image
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$SHORT_SHA

          echo "Building $IMAGE_URI"
          docker build -t $IMAGE_URI -f Dockerfile .
          docker push $IMAGE_URI

          echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::959413831332:role/eks-ci-role
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init/Apply (greeter)
        working-directory: ./greeter
        env:
          TF_VAR_image_repository: 959413831332.dkr.ecr.eu-central-1.amazonaws.com/greeter
          TF_VAR_image_tag: ${{ needs.build-and-push.outputs.image_tag }}
          TF_VAR_hello_tag: ${{ github.run_number }}
        run: |
          terraform init -input=false
          terraform apply -input=false -auto-approve