# .github/workflows/build-and-push.yml
name: Build & Push
on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::959413831332:role/eks-ci-role
          aws-region: eu-central-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-central-1 \
            | docker login --username AWS --password-stdin 959413831332.dkr.ecr.eu-central-1.amazonaws.com

      - name: Build & Push
        env:
          REPO: 959413831332.dkr.ecr.eu-central-1.amazonaws.com/greeter
          TAG:  ${{ github.sha }}
        run: |
          docker build -t $IMAGE_REPO:${{ github.sha }} -f Dockerfile .
          docker push $IMAGE_REPO:${{ github.sha }}
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::959413831332:role/eks-ci-role
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init/Apply (greeter)
        working-directory: infra/envs/dev/greeter
        env:
          TF_VAR_image_repository: 959413831332.dkr.ecr.eu-central-1.amazonaws.com/greeter
          TF_VAR_image_tag: ${{ needs.build-and-push.outputs.image_tag || github.sha }}
          TF_VAR_hello_tag: ${{ github.run_number }}
        run: |
          terraform init -input=false
#          terraform apply -input=false -auto-approve \
#            -var image_repository=${{ env.TF_VAR_image_repository }} \
#            -var image_tag=${{ env.TF_VAR_image_tag }} \
#            -var hello_tag=${{ env.TF_VAR_hello_tag }}